{% set version="3.20.0" %}
{% set name="edgeR" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 3d0a0c0058cf62f6fbc35a53c6562d60482be0a3168eb10e31e994699a0d02b3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - r-base
    - r-locfit
    - r-rcpp
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-limma
    - r-base
    - r-locfit
    - r-rcpp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Differential expression analysis of RNA-seq expression profiles with biological replication. Implements a range of statistical methodology based on the negative binomial distributions, including empirical Bayes estimation, exact tests, generalized linear models and quasi-likelihood tests. As well as RNA-seq, it be applied to differential signal analysis of other types of genomic data that produce counts, including ChIP-seq, Bisulfite-seq, SAGE and CAGE.'
