{% set version="2.5.6" %}
{% set name="rols" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2d38c93e12d034efdc9f5dd7332363a3d6b82ffce1c399614c62cff49534e079
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.23.1'
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.23.1'
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The rols package is an interface to the Ontology Lookup Service (OLS) to access and query hundred of ontolgies directly from R.'
