build:
  number: 0

package:
  name: cms
  version: "2.0.0"

source:
  git_rev: v0.0.0 #JV needs to publish release: https://github.com/broadinstitute/cms/releases/new
  git_url: https://github.com/broadinstitute/cms.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pyinstrument

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pyinstrument --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://broad-cms.readthedocs.io/en/latest/
  license: GPLv3
  summary: "CMS (composite of multiple signals) is a suite of tools for resolving signatures of recent positive selection in population genetic data."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
