build:
  number: 0

package:
  name: cms
  version: "2.0.0b"

source:
  fn: cms-2.0.0-beta.tar.gz
  url: https://github.com/broadinstitute/cms/archive/2.0.0-beta.tar.gz
  md5: 3e5754bf0a6eeb71cc483dcdae10d8c0

requirements:
  build:
    #- python
    - gcc
    - llvm

  run:
    #- python
    - libgcc 

test:
  commands:
    - "bootstrap_freq_popstats_regions &> /dev/null"
    #- "python cms/likes_from_model.py | grep 'model' &> /dev/null"
about:
  home: http://broad-cms.readthedocs.io/en/latest/
  license: GPLv3
  summary: "CMS (composite of multiple signals) is a suite of tools for resolving signatures of recent positive selection in population genetic data."
