{% set version = "1.2.0" %}

package:
    name: magicblast
    version: {{ version }}

source:
    fn: ncbi-magicblast-{{ version }}+-src.tar.gz # [linux]
    url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/magicblast/{{ version }}/ncbi-magicblast-{{ version }}-src.tar.gz # [linux]
    md5: 29798e5944cbdc7c755958572ccd62b2 # [linux]
    fn: ncbi-magicblast-{{ version }}+-x64-macosx.tar.gz # [osx]
    url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/magicblast/{{ version }}/ncbi-magicblast-{{ version }}-x64-macosx.tar.gz # [osx]
    md5: b681429c4b073d325c1af1a1d425b797 # [osx]

build:
  number: 0
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

requirements:
  build:
    - boost {{CONDA_BOOST}}*  # [linux]
    - gcc  # [linux]
  run:
    - boost {{CONDA_BOOST}}*  # [linux]
    - libgcc  # [linux]

test:
    commands:
        - magicblast -help > /dev/null

about:
    home: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/magicblast/
    license: Public Domain
    summary: Magic-BLAST is a tool for mapping large next-generation RNA or DNA sequencing runs against a whole genome or transcriptome
