{% set version="1.51.0" %}
{% set name="PGSEA" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 293d51c238fe7ec0df23755670b36f53dc7022f06cb3558913e8bf518162ed0d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annaffy
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-go.db
    - bioconductor-kegg.db
    - r-base
  run:
    - bioconductor-annaffy
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-go.db
    - bioconductor-kegg.db
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Parametric Analysis of Gene Set Enrichment'
