{% set version="1.16.0" %}
{% set name="TitanCNA" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 460b44b40d5ab47156ec7cb4cac09650fb2ec00581198e7c3a1d375b0b00ae03
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-genomeinfodb >=1.8.7'
    - 'bioconductor-genomicranges >=1.24.3'
    - 'bioconductor-iranges >=2.6.1'
    - 'bioconductor-rsamtools >=1.24.0'
    - 'bioconductor-variantannotation >=1.18.7'
    - r-base
    - 'r-data.table >=1.10.4'
    - 'r-dplyr >=0.5.0'
    - 'r-foreach >=1.4.3'
  run:
    - 'bioconductor-genomeinfodb >=1.8.7'
    - 'bioconductor-genomicranges >=1.24.3'
    - 'bioconductor-iranges >=2.6.1'
    - 'bioconductor-rsamtools >=1.24.0'
    - 'bioconductor-variantannotation >=1.18.7'
    - r-base
    - 'r-data.table >=1.10.4'
    - 'r-dplyr >=0.5.0'
    - 'r-foreach >=1.4.3'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Hidden Markov model to segment and predict regions of subclonal copy number alterations (CNA) and loss of heterozygosity (LOH), and estimate cellular prevalenece of clonal clusters in tumour whole genome sequencing data.'
