{% set version="2.46.0" %}
{% set name="GEOquery" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 81c23d9bc262c6a8ff9602a97c29a9e726726a49c2b51bb123d2a26b969b2a13
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - r-base
    - r-dplyr
    - r-httr
    - r-magrittr
    - r-rcurl
    - r-readr
    - r-tidyr
    - r-xml
    - r-xml2
  run:
    - bioconductor-biobase
    - r-base
    - r-dplyr
    - r-httr
    - r-magrittr
    - r-rcurl
    - r-readr
    - r-tidyr
    - r-xml
    - r-xml2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The NCBI Gene Expression Omnibus (GEO) is a public repository of microarray data.  Given the rich and varied nature of this resource, it is only natural to want to apply BioConductor tools to these data.  GEOquery is the bridge between GEO and BioConductor.'
