{% set version="1.10.0" %}
{% set name="rGREAT" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 599507abb002938d6c8ca9bc19fc2aa722fba2b08e47296be76167fdc1dc7cda
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-genomicranges
    - bioconductor-iranges
    - r-base
    - 'r-getoptlong >=0.0.9'
    - r-rcurl
    - r-rjson
  run:
    - bioconductor-genomicranges
    - bioconductor-iranges
    - r-base
    - 'r-getoptlong >=0.0.9'
    - r-rcurl
    - r-rjson
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This package makes GREAT (Genomic Regions Enrichment of Annotations Tool) analysis automatic by constructing a HTTP POST request according to user''s input and automatically retrieving results from GREAT web server.'
