package:
  name: coveralls
  version: "1.1"

source:
  fn: coveralls-1.1.tar.gz
  url: https://pypi.python.org/packages/12/50/5c1034eb92e5bc3d824a3745ca9162f2e4846c6ab5f96dccb5f84f77e98f/coveralls-1.1.tar.gz
  md5: 3b4431f7d38ceb3ff4e47cb8361f3333
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - coveralls = coveralls:main
    #
    # Would create an entry point called coveralls that calls coveralls.main()

    - coveralls = coveralls.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docopt >=0.6.1
    - coverage >=3.6
    - requests >=1.0.0

  run:
    - python
    - docopt >=0.6.1
    - coverage >=3.6
    - requests >=1.0.0

test:
  # Python imports
  imports:
    - coveralls

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - coveralls --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - pytest >=2.7.3,<2.8
    - sh >=1.08
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/coagulant/coveralls-python
  license: MIT License
  summary: 'Show coverage stats online via coveralls.io'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
