{% set version="2.10.0" %}
{% set name="AnnotationHub" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 0bf9b3771adc1a0f7f57b7423e5f163a20bce25b053561cd9e10f1cf869a2eab
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=1.31.19'
    - 'bioconductor-biocgenerics >=0.15.10'
    - bioconductor-biocinstaller
    - bioconductor-interactivedisplaybase
    - bioconductor-s4vectors
    - r-base
    - r-curl
    - r-httr
    - r-rsqlite
    - r-yaml
  run:
    - 'bioconductor-annotationdbi >=1.31.19'
    - 'bioconductor-biocgenerics >=0.15.10'
    - bioconductor-biocinstaller
    - bioconductor-interactivedisplaybase
    - bioconductor-s4vectors
    - r-base
    - r-curl
    - r-httr
    - r-rsqlite
    - r-yaml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package provides a client for the Bioconductor AnnotationHub web resource. The AnnotationHub web resource provides a central location where genomic files (e.g., VCF, bed, wig) and other resources from standard locations (e.g., UCSC, Ensembl) can be discovered. The resource includes metadata about each resource, e.g., a textual description, tags, and date of modification. The client creates and manages a local cache of files retrieved by the user, helping with quick and reproducible access.'
