{% set version="1.15.0" %}
{% set name="PSICQUIC" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 80616084e36571abe6850aba4235d5252ad76cc4f15fc96c9c3e80c3369a894a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-iranges
    - r-base
    - r-httr
    - r-plyr
    - r-rcurl
  run:
    - bioconductor-biocgenerics
    - bioconductor-biomart
    - bioconductor-iranges
    - r-base
    - r-httr
    - r-plyr
    - r-rcurl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Apache License 2.0'
  summary: 'PSICQUIC is a project within the HUPO Proteomics Standard Initiative (HUPO-PSI).  It standardises programmatic access to molecular interaction databases.'
