{% set version="1.16.0" %}
{% set name="ComplexHeatmap" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 07a4b04da2cb5186b08f9206e7c26b34045b9e1ada55a6ff962045b28d98d8ee
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - 'r-circlize >=0.4.1'
    - r-colorspace
    - r-getoptlong
    - 'r-globaloptions >=0.0.10'
    - r-rcolorbrewer
  run:
    - r-base
    - 'r-circlize >=0.4.1'
    - r-colorspace
    - r-getoptlong
    - 'r-globaloptions >=0.0.10'
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Complex heatmaps are efficient to visualize associations between different sources of data sets and reveal potential structures. Here the ComplexHeatmap package provides a highly flexible way to arrange multiple heatmaps and supports self-defined annotation graphics.'
