{% set version="3.4.2" %}
{% set name="org.Bt.eg.db" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a71ed95c45738d86b2e35592ce005acceb65f281bc7cce9505b2d14e2be26341
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=1.39.3'
    - r-base
  run:
    - 'bioconductor-annotationdbi >=1.39.3'
    - r-base
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Genome wide annotation for Bovine, primarily based on mapping using Entrez Gene identifiers.'
