{% set version = "0.1.8" %}

package:
  name: taxonkit
  version: {{ version }}

about:
  home: https://github.com/shenwei356/taxonkit
  summary: A Cross-platform and Efficient NCBI Taxonomy Toolkit
  license: MIT

build:
  number: 0
  skip: False

source:
  fn: taxonkit_v{{ version }}_osx.tar.gz # [osx]
  url: https://github.com/shenwei356/taxonkit/releases/download/v{{ version }}/taxonkit_darwin_amd64.tar.gz # [osx]
  md5: 8142fe0150a3509c205d3eb4f07ef3df # [osx]
  
  fn: taxonkit_v{{ version }}_linux.tar.gz # [linux]
  url: https://github.com/shenwei356/taxonkit/releases/download/v{{ version }}/taxonkit_linux_386.tar.gz # [linux]
  md5: a71fbc8455b91d579fd3619fba356bbb # [linux]

  fn: taxonkit_v{{ version }}_linux64.tar.gz # [linux64]
  url: https://github.com/shenwei356/taxonkit/releases/download/v{{ version }}/taxonkit_linux_amd64.tar.gz # [linux64]
  md5: 09532b0a71f04f0c3a4b5117cea736c1 # [linux64]

test:
  commands:
    - taxonkit version --help


