{% set version="1.11.0" %}
{% set name="Rnits" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 4b5f1898a4cfbd6fe5b77fa8287d4fb723791742d0167981d0f61c5b66f24edd
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-qvalue
    - r-base
    - r-boot
    - r-ggplot2
    - r-reshape2
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-qvalue
    - r-base
    - r-boot
    - r-ggplot2
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'R/Bioconductor package for normalization, curve registration and inference in time course gene expression data'
