package:
  name: ngmlr
  version: '0.2.2'

source:
  fn: ngmlr-v0.2.2.tar.gz
  url: "https://github.com/philres/ngmlr/archive/v0.2.2.tar.gz"
  md5: "51e4e62bbfb95a29f2ac253d44c5b606"

build:
  number: 1

requirements:
  build:
    - gcc >=4.8.2   # [linux]
    - llvm  # [osx]
    - cmake
    - zlib {{CONDA_ZLIB}}*
  run:
    - zlib {{CONDA_ZLIB}}*
    - libgcc  # [linux]

test:
  commands:
    - ngmlr --help

about:
  home: https://github.com/philres/ngmlr
  license: GPL-3.0
  summary: ngmlr is a long-read mapper desigend to align PacBilo or Oxford Nanopore to a reference genome optimized for structural variation detection
