{% set name = "lap" %}
{% set version = "1.1.r186" %}
{% set md5 = "ddff881a64976a7a61dd4229442ae198" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: lap_1.1.r186_src_all.zip
  url: https://depot.galaxyproject.org/software/lap/lap_1.1.r186_src_all.zip
  md5: {{ md5 }}

build:
  number: 1
  skip: True # [not py27 or osx]

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]

  run:
    - libgcc    # [not osx]
    - python
    - bowtie2

test:
  commands:
    - calc_prob.py --help
    - gen_rand_samp.py --help
    - sum_prob.py --help
    - mean --help
    - probability --help
    - mprobability --help
    - sample --help
    - stitch --help

about:
  home: http://assembly-eval.sourceforge.net/
  license: 'GPL'
  summary: 'De novo genome assembly evaluation'
