package:
  name: bcbio-nextgen-vm
  version: '0.1.0a'

build:
  number: 93
  skip: True # [not py27]

source:
  fn: bcbio-nextgen-vm-b555c36.tar.gz
  url: https://github.com/chapmanb/bcbio-nextgen-vm/archive/b555c36.tar.gz
  md5: e68737569ee343b9562beb012436e017

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bcbio-nextgen >1.0.2
    - ipyparallel >=4.0,<5.0
    - pysam >=0.11.0
    - arvados-cwl-runner
    - cwl2wdl
    - toil
    - nodejs
    - elasticluster
    - nose
    - six

test:
  imports:
    - bcbiovm.version
  commands:
    - bcbio_vm.py -h

about:
  home: https://github.com/chapmanb/bcbio-nextgen-vm
  license: MIT
  summary: Run bcbio-nextgen genomic sequencing analyses using isolated containers and virtual machines
