{% set version="1.6.0" %}
{% set name="flowAI" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 3047117e1e8193b0875654d72ebb611291c99b69171de6ccd015df64651e97b5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-flowcore
    - r-base
    - r-changepoint
    - r-ggplot2
    - r-knitr
    - r-plyr
    - r-rcolorbrewer
    - r-reshape2
    - r-scales
  run:
    - bioconductor-flowcore
    - r-base
    - r-changepoint
    - r-ggplot2
    - r-knitr
    - r-plyr
    - r-rcolorbrewer
    - r-reshape2
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL
  summary: 'The package is able to perform an automatic or interactive quality control on FCS data acquired using flow cytometry instruments. By evaluating three different properties: 1) flow rate, 2) signal acquisition, 3) dynamic range, the quality control enables the detection and removal of anomalies.'
