{% set version="1.23.0" %}
{% set name="CellNOptR" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a7f2c30433ad8a4c48c64f1fddc164392250a06bb0b7ebace6b84a8d4d7a06e4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
    - r-ggplot2
    - r-hash
    - r-rcurl
    - r-xml
  run:
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - r-base
    - r-ggplot2
    - r-hash
    - r-rcurl
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'This package does optimisation of boolean logic networks of signalling pathways based on a previous knowledge network and a set of data upon perturbation of the nodes in the network.'
