{% set version="1.18.0" %}
{% set name="DESeq2" %}
{% set bioc="3.6" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: d0431655e93f74cad96ec3487e7ea0561e2c3587ba451c9184e46f27e7b49dc1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-biocparallel
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
    - r-ggplot2
    - r-hmisc
    - r-locfit
    - 'r-rcpp >=0.11.0'
    - r-rcpparmadillo
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-biocparallel
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - bioconductor-genomicranges
    - bioconductor-iranges
    - 'bioconductor-s4vectors >=0.9.25'
    - 'bioconductor-summarizedexperiment >=1.1.6'
    - r-base
    - r-ggplot2
    - r-hmisc
    - r-locfit
    - 'r-rcpp >=0.11.0'
    - r-rcpparmadillo
    # optional dependencies
    - bioconductor-tximport
    - r-rjson
    - r-hmisc
    - r-getopt
    - r-gplots

test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 3)'
  summary: 'Estimate variance-mean dependence in count data from high-throughput sequencing assays and test for differential expression based on a model using the negative binomial distribution.'
